#!/usr/bin/env bash
# Copyright 2026 Alessandro Masat
# SPDX-License-Identifier: Apache-2.0
#
# make_wrapper.sh <tool> <real-binary> <wrapper-dir> [log-dir]
#
# Writes <wrapper-dir>/<basename of real-binary>: an executable script that `exec`s the
# sanitizer tool on the real binary with the tool's error exit code, so
#
#   tests/check_gate.sh <cuda|cpp> <wrapper-dir>/<binary-name>
#
# gives the env-scrubbed listing, the run, the manifest comparison and the tool's exit
# status in ONE command (check_gate.sh only needs an executable whose basename it runs).
# The wrapper runs from the real binary's directory.
#
# <tool>: valgrind | memcheck | racecheck | synccheck | initcheck   (the last four are
#         NVIDIA compute-sanitizer tools). Exit 77 = a tool finding; anything else is the
#         target's own status.
# Logs: <log-dir>/<tool>.<pid>.log (default <wrapper-dir>/logs); the suppressed count is
#       on valgrind's "ERROR SUMMARY" line.
set -euo pipefail
[ $# -ge 3 ] || { sed -n '4,20p' "$0" >&2; exit 2; }
TOOL="$1"; REAL="$2"; WDIR="$3"
[ -x "$REAL" ] || { echo "make_wrapper: '$REAL' is not an executable file" >&2; exit 2; }
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p "$WDIR"
REAL="$(cd "$(dirname "$REAL")" && pwd)/$(basename "$REAL")"
WDIR="$(cd "$WDIR" && pwd)"
LOGDIR="${4:-$WDIR/logs}"; mkdir -p "$LOGDIR"; LOGDIR="$(cd "$LOGDIR" && pwd)"
OUT="$WDIR/$(basename "$REAL")"

case "$TOOL" in
    valgrind)
        SUPP=""
        for f in "$SELF_DIR"/suppressions/*.supp; do SUPP="$SUPP --suppressions=$f"; done
        TOOLCMD="valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=definite,indirect,possible --error-exitcode=77 --track-origins=yes --num-callers=25 --child-silent-after-fork=yes --log-file=$LOGDIR/valgrind.%p.log$SUPP" ;;
    memcheck)
        TOOLCMD="compute-sanitizer --tool=memcheck --leak-check=full --report-api-errors no --padding=256 --launch-timeout=60 --error-exitcode=77 --log-file=$LOGDIR/computesan.memcheck.%p.log" ;;
    racecheck|synccheck|initcheck)
        TOOLCMD="compute-sanitizer --tool=$TOOL --leak-check=full --launch-timeout=60 --error-exitcode=77 --log-file=$LOGDIR/computesan.$TOOL.%p.log" ;;
    *) echo "make_wrapper: unknown tool '$TOOL'" >&2; exit 2 ;;
esac

{
    echo '#!/usr/bin/env bash'
    echo "# generated by make_wrapper.sh ($TOOL); do not edit"
    echo "cd \"$(dirname "$REAL")\""
    echo '# the test listing never reaches the device: run it uninstrumented'
    echo "case \" \$* \" in *\" --gtest_list_tests \"*) exec \"$REAL\" \"\$@\" ;; esac"
    echo "exec $TOOLCMD \"$REAL\" \"\$@\""
} > "$OUT"
chmod +x "$OUT"
echo "$OUT"
